<a href="https://colab.research.google.com/github/Reddysaikowshik/PYTHON-FOR-DATA-SCIENCE/blob/main/Assignment_06_ipynb_(18th_Aug).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

print("=== 2D Broadcasting Example ===")
A = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print("Array A:\n", A)
print("Shape of A:", A.shape)
print("Array b:", b)
print("Shape of b:", b.shape)

C = A + b
print("A + b =\n", C)
print("Result shape:", C.shape)
print()

print("=== Broadcasting Rules Explanation ===")
print("Shapes compared from right to left:")
print(" A.shape = (2, 3)")
print(" b.shape = (3,)")
print(" -> b is treated as (1, 3)")
print(" -> Dimensions align, so broadcasting works.")
print()

print("=== 3D Broadcasting with Scalar ===")
X = np.ones((2, 3, 4))
scalar = 5

print("Array X shape:", X.shape)
print("Scalar:", scalar)

Y = X + scalar
print("X + scalar =\n", Y)
print("Result shape:", Y.shape)
print("Explanation: Scalar is treated as shape (1, 1, 1).")
print()

print("=== Using np.newaxis ===")
d = np.array([1, 2, 3])

print("Original d shape:", d.shape)

d_col = d[:, np.newaxis]
print("d_col shape:", d_col.shape)
print("d_col:\n", d_col)

M = np.array([[10, 20, 30],
                            [40, 50, 60],
                            [70, 80, 90]])

print("M shape:", M.shape)

result = M + d_col
print("M + d_col =\n", result)
print("Result shape:", result.shape)
print("Explanation: d_col (3,1) is broadcast across columns.")
print()

print("=== Invalid Broadcasting Case ===")
P = np.ones((2, 3))
Q = np.ones((3, 2))

print("P shape:", P.shape)
print("Q shape:", Q.shape)

try:
    Z = P + Q
except ValueError as e:
    print("Error:", e)
    print("Explanation: Shapes (2,3) and (3,2) are incompatible.")

=== 2D Broadcasting Example ===
Array A:
 [[1 2 3]
 [4 5 6]]
Shape of A: (2, 3)
Array b: [10 20 30]
Shape of b: (3,)
A + b =
 [[11 22 33]
 [14 25 36]]
Result shape: (2, 3)

=== Broadcasting Rules Explanation ===
Shapes compared from right to left:
 A.shape = (2, 3)
 b.shape = (3,)
 -> b is treated as (1, 3)
 -> Dimensions align, so broadcasting works.

=== 3D Broadcasting with Scalar ===
Array X shape: (2, 3, 4)
Scalar: 5
X + scalar =
 [[[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]

 [[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]]
Result shape: (2, 3, 4)
Explanation: Scalar is treated as shape (1, 1, 1).

=== Using np.newaxis ===
Original d shape: (3,)
d_col shape: (3, 1)
d_col:
 [[1]
 [2]
 [3]]
M shape: (3, 3)
M + d_col =
 [[11 21 31]
 [42 52 62]
 [73 83 93]]
Result shape: (3, 3)
Explanation: d_col (3,1) is broadcast across columns.

=== Invalid Broadcasting Case ===
P shape: (2, 3)
Q shape: (3, 2)
Error: operands could not be broadcast together with shapes (2,3) (3,2) 
Explanation